# syntax=docker/dockerfile:1

ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV production

ARG FS22_BOT_DB_PATH
ARG FS22_BOT_DISABLE_CERTIFICATE_VERIFICATION
ARG FS22_BOT_DISABLE_UNREACHABLE_FOUND_MESSAGES
ARG FS22_BOT_DISCORD_CHANNEL_NAME
ARG FS22_BOT_DISCORD_SERVER_NAME
ARG FS22_BOT_DISCORD_TOKEN
ARG FS22_BOT_FETCH_RETRIES
ARG FS22_BOT_FETCH_RETRY_DELAY_MS
ARG FS22_BOT_POLL_INTERVAL_MINUTES
ARG FS22_BOT_PURGE_DISCORD_CHANNEL_AFTER_DAYS
ARG FS22_BOT_PURGE_DISCORD_CHANNEL_AFTER_LINES
ARG FS22_BOT_PURGE_DISCORD_CHANNEL_HOUR
ARG FS22_BOT_PURGE_DISCORD_CHANNEL_NAME
ARG FS22_BOT_PURGE_DISCORD_CHANNEL_SERVER_NAME
ARG FS22_BOT_URL_CAREER_SAVEGAME
ARG FS22_BOT_URL_SERVER_STATS

WORKDIR /usr/src/app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

USER node

COPY . .

CMD [ "node", "./bin/server.js" ]
